### ISSUE TITLE
compile error：warning: can't open  /home/work/kvdb/pear/v0.1.0/pear_syn/0.pear :(    parser.c parse : 267

### ISSUE THREAD

**Issue by Sander-houqi** [UncP/pear#1]
gcc -std=c99 -Wall -O3   -c -o util.o util.c
gcc -std=c99 -Wall -O3   -c -o file.o file.c
file.c: In function ‘new_file’:
file.c:54:8: warning: implicit declaration of function ‘truncate64’ [-Wimplicit-function-declaration]
   if (!truncate64(buf, 0)) {
        ^
gcc -std=c99 -Wall -O3   -c -o page.o page.c
page.c: In function ‘_write_page’:
page.c:22:6: warning: implicit declaration of function ‘pwrite’ [-Wimplicit-function-declaration]
  if (pwrite(page->fd, page->data, page_size, offset) != page_size)
      ^
page.c: In function ‘_read_page’:
page.c:31:6: warning: implicit declaration of function ‘pread’ [-Wimplicit-function-declaration]
  if (pread(page->fd, page->data, page_size, offset) < page_size)
      ^
gcc -std=c99 -Wall -O3   -c -o btree.o btree.c
gcc -std=c99 -Wall -O3   -c -o table.o table.c
gcc -std=c99 -Wall -O3   -c -o db.o db.c
gcc -std=c99 -Wall -O3   -c -o parser.o parser.c
parser.c: In function ‘_next_buffer’:
parser.c:74:22: warning: implicit declaration of function ‘pread’ [-Wimplicit-function-declaration]
  parser.buffer.len = pread(parser.fd, parser.buffer.mem, BUFFER_SIZE, parser.processed);
                      ^
gcc -std=c99 -Wall -O3 -pg -o pear util.o file.o page.o btree.o table.o db.o parser.o pear.c
make: 'pear' is up to date.
warning:无法打开 /home/work/kvdb/pear/v0.1.0/pear_syn/0.pear :(
parser.c 	parse : 267
warning:无法打开 /home/work/kvdb/pear/v0.1.0/pear_syn/1.pear :(
parser.c 	parse : 267
warning:无法打开 /home/work/kvdb/pear/v0.1.0/pear_syn/2.pear :(
parser.c 	parse : 267
../my/gmon.out: No such file or directory
rm: cannot remove '../my/gmon.out': No such file or directory
.003436111

**Comment by UncP** [comment]
你的Linux系统是多少位的，什么版本？

**Comment by Sander-houqi** [comment]
ubuntu 16.04 LTS ，64位

**Comment by UncP** [comment]
那些warning应该可以忽略。你还没有生成测试文件，需要在v0.1.0这个文件夹里输入python generate_data.py

**Comment by Sander-houqi** [comment]
python generate_data.py 这个文件肯定是有的啊，要不之前就会报错了，我之前是解决过python和anaconda冲突的问题的。

**Comment by UncP** [comment]
我这也是相同的问题，那些warning可以忽略的，不影响程序运行，但是你现在生成测试文件没有，如果没有的话运行generate_data.py这个文件。

**Comment by Sander-houqi** [comment]
测试文件不就是pear_syn 么，里面有200个

**Comment by UncP** [comment]
那应该是你open函数出问题了吧，如果文件存在的话，你看下parser.c这个文件的267行。

**Comment by Sander-houqi** [comment]
找见问题了，是你的generate.data中创建目录的问题，应该改为../pear_syn,否则会在src下生成测试文件。
另外，你的readme中的 cd pear/v0.1.0  应该改为 cd pear/v0.1.0/src ,否则不能make啦

**Comment by UncP** [comment]
嗯
